### ISSUE TITLE
希望可以增加tldraw白板

### ISSUE THREAD

**Issue by wtfsb19** [revezone/revezone#11]
tldraw跟Excalidraw类似，但tldraw在流程图操作上的自由度和操作性要更流畅一些，希望可以添加选项可以在两种白板之间进行切换。辛苦大佬。
tldraw也是开源的，其GitHub地址：https://github.com/tldraw/tldraw
其在线网站：https://www.tldraw.com/

**Comment by korbinzhao** [comment]
@wtfsb19 感谢建议 👍 ，我先体验下 tldraw 哈

**Comment by wtfsb19** [comment]
> @wtfsb19 感谢建议 👍 ，我先体验下 tldraw 哈

tldraw在移动元素时可以按CTRL来实现类似Photoshop那样的自动对齐，我觉得这个功能很实用，强迫症大满足。😊

**Comment by korbinzhao** [comment]
@wtfsb19 体验了 tldraw，确实不错，是一种和 Excalidraw 相比挺不一样的体验。Revezone 已正式将 Tldraw 的集成纳入开发计划，近期就会支持掉。敬请期待哈。

**Comment by korbinzhao** [comment]
@wtfsb19 tldraw 已经在最新 release 中支持，欢迎下载体验

**Comment by xulei-shl** [comment]
双击全选文本时，界面没有显示背景色样式，虽然实际上是全选的。同样的，鼠标滑动选择文本，也没有显示
![image](https://github.com/revezone/revezone/assets/13896259/679b5cef-bd23-4d22-9c6f-f9c1a0527a8a)

**Comment by korbinzhao** [comment]
> 双击全选文本时，界面没有显示背景色样式，虽然实际上是全选的。同样的，鼠标滑动选择文本，也没有显示。下图是https://www.tldraw.com 官网的正常样式 ![image](https://user-images.githubusercontent.com/13896259/269184915-679b5cef-bd23-4d22-9c6f-f9c1a0527a8a.png)

感谢反馈，确实是个bug，我定位解决下哈

**Comment by wtfsb19** [comment]
> @wtfsb19 tldraw 已经在最新 release 中支持，欢迎下载体验

感谢采纳，已经体验到了，感谢大大😆
