### ISSUE TITLE
有没有mac intel的安装包

### ISSUE THREAD

**Issue by Hsiao-Jan** [revezone/revezone#6]
如题，下载下来的dmg文件是arm64的，有没有办法提供amd的？

**Comment by korbinzhao** [comment]
感谢反馈，晚些时候提供出来哈

**Comment by Hsiao-Jan** [comment]
> 感谢反馈，晚些时候提供出来哈

麻烦了 谢谢谢谢

**Comment by korbinzhao** [comment]
已在最新版新增 x64 包，不过我电脑不是 intel 芯片的，还没进行安装验证，可以试下。如果安装有问题，及时反馈我哈。

**Comment by Hsiao-Jan** [comment]
> @Hsiao-Jan 已在最新版新增 x64 包，不过我电脑不是 intel 芯片的，还没进行安装验证，可以试下。如果安装有问题，反馈我解决哈。

已经成功安装，暂时未发现其他问题，感谢！待使用后反馈
